export const experiences = [
    {
        id: 1,
        company: "Astitva Foundation",
        logo: "/astitva.png",
        link: "https://astitvafoundation.vercel.app/",
        role: "Co-Founder & Lead",
        duration: "January 2025 - Present",
        location: "Jorhat, Assam",
        skills: ["React", "Tailwind CSS", "Node.js", "Mogodb", "Express.js"],
    },
    {
        id: 2,
        company: "IIT Guwahati",
        logo: "/IITG_logo.png",
        link: "https://iitg.ac.in/",
        role: "Research Intern",
        duration: "June 2024 - July 2024",
        location: "Guwahati, India",
        skills: ["Python", "Tensorflow", "NLP", "Deep Learning"],
    },
    {
        id: 3,
        company: "Ideal Abhijan",
        logo: "/ideal_abhijan.jpg",
        link: "https://www.idealabhijan.co.in/",
        role: "Social Intern",
        duration: "June 2023 - July 2023",
        location: "Jorhat, India",
        skills: ["Public Speaking", "Audience Analysis", "Team Management"],
    },
];
